# Generated by Django 5.2.6 on 2025-09-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPerdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Item Perdido')),
            ],
            options={
                'verbose_name': 'Item Perdido',
                'verbose_name_plural': 'Itens Perdidos ',
            },
        ),
    ]
