# Generated by Django 5.2.6 on 2025-09-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_itemachado_data_itemachado_foto_itemperdido_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemachado',
            name='local',
            field=models.CharField(choices=[('Biblioteca', 'Biblioteca')], default='Sem local'),
        ),
    ]
