# Generated by Django 5.2.6 on 2025-09-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_itemachado_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemperdido',
            name='local',
            field=models.CharField(choices=[('Biblioteca', 'Biblioteca'), ('Campo', 'Campo')], default='Não sei aonde perdi'),
        ),
        migrations.AlterField(
            model_name='itemachado',
            name='local',
            field=models.CharField(choices=[('Biblioteca', 'Biblioteca'), ('Campo', 'Campo')], default='Sem local'),
        ),
    ]
