# Generated by Django 5.2.6 on 2025-09-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_itemachado_options_alter_itemperdido_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemperdido',
            name='categoria',
            field=models.CharField(choices=[('Roupa', 'Roupa'), ('Eletrônico', 'Eletrônico'), ('Livro', 'Livro'), ('Documento', 'Documento'), ('Chave', 'Chave'), ('Acessório', 'Acessório'), ('Brinquedo', 'Brinquedo'), ('Mochila', 'Mochila'), ('Celular', 'Celular'), ('Óculos', 'Óculos')], default='Sem categoria'),
        ),
    ]
