# Generated by Django 5.2.8 on 2025-11-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAchado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Item Achado')),
                ('desc', models.TextField(default='Sem descrição', max_length=250, verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data que o item foi Perdido')),
                ('local', models.CharField(choices=[('Biblioteca', 'Biblioteca'), ('Predio do Café', 'Predio do Café'), ('Agronomia', 'Agronomia'), ('Celin', 'Celin'), ('Predio da informatica', 'Predio da informatica'), ('Refeitorio', 'Refeitorio'), ('Predio H', 'Predio H'), ('Lanchonete', 'Lanchonete'), ('Coopam', 'Coopam'), ('Quadra', 'Quadra'), ('Poli esportivo', 'Poli esportivo'), ('Tatame', 'Tatame'), ('Academia', 'Academia'), ('Selca', 'Selca'), ('Sala de jogos', 'Sala de jogos'), ('Alojamento A', 'Alojamento A'), ('Alojamento B', 'Alojamento B'), ('Alojamento C', 'Alojamento C'), ('Hospital Veterinario', 'Hospital Veterinario'), ('Z3 de Leite', 'Z3 de leite'), ('Z3 de corte', 'Z3 de corte'), ('Caprino', 'Caprino'), ('Suino', 'Suino'), ('Cunicultura', 'Cunicultura'), ('Cecaes', 'Cecaes')], default='Sem local')),
                ('categoria', models.CharField(choices=[('Roupa', 'Roupa'), ('Eletrônico', 'Eletrônico'), ('Livro', 'Livro'), ('Documento', 'Documento'), ('Chave', 'Chave'), ('Acessório', 'Acessório'), ('Brinquedo', 'Brinquedo'), ('Mochila', 'Mochila'), ('Celular', 'Celular'), ('Óculos', 'Óculos')], default='Sem categoria')),
            ],
            options={
                'verbose_name_plural': 'AcheiUmItem',
            },
        ),
        migrations.CreateModel(
            name='ItemPerdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('descricao', models.TextField()),
                ('local', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('tipoContato', models.CharField(max_length=20)),
                ('contato', models.CharField(max_length=100)),
                ('recompensa', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
