# Generated by Django 5.2.6 on 2025-09-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAchado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Item Achado')),
            ],
            options={
                'verbose_name': 'Item Achado',
                'verbose_name_plural': 'Itens Achados ',
            },
        ),
    ]
