# Generated by Django 5.2.6 on 2025-09-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_itemachado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemachado',
            options={'verbose_name': 'Item Achado', 'verbose_name_plural': 'Itens Achados'},
        ),
    ]
