# Generated by Django 5.2.6 on 2025-09-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_itemachado_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemachado',
            name='desc',
            field=models.TextField(default='Sem descrição', max_length=250, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='itemperdido',
            name='desc',
            field=models.TextField(default='Sem descrição', max_length=250, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='itemperdido',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
