# Generated by Django 5.2.6 on 2025-09-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_itemachado_desc_itemperdido_desc_itemperdido_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemachado',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data que o item foi Perdido'),
        ),
        migrations.AddField(
            model_name='itemachado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='itemperdido',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data que o item foi Perdido'),
        ),
    ]
