# Generated by Django 5.2.6 on 2025-09-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_itemperdido_local_alter_itemachado_local'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemperdido',
            options={'verbose_name': 'PerdiMeuItem'},
        ),
        migrations.AlterField(
            model_name='itemperdido',
            name='local',
            field=models.CharField(choices=[('Não sei', 'Não sei'), ('Biblioteca', 'Biblioteca'), ('Campo', 'Campo')], default='Não sei aonde perdi'),
        ),
    ]
