# Generated by Django 5.2.6 on 2025-09-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_itemperdido_options_alter_itemperdido_local'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemachado',
            options={'verbose_name_plural': 'AcheiUmItem'},
        ),
        migrations.AlterModelOptions(
            name='itemperdido',
            options={'verbose_name_plural': 'PerdiMeuItem'},
        ),
        migrations.AddField(
            model_name='itemachado',
            name='categoria',
            field=models.CharField(choices=[('Roupa', 'Roupa'), ('Eletrônico', 'Eletrônico'), ('Livro', 'Livro'), ('Documento', 'Documento'), ('Chave', 'Chave'), ('Acessório', 'Acessório'), ('Brinquedo', 'Brinquedo'), ('Mochila', 'Mochila'), ('Celular', 'Celular'), ('Óculos', 'Óculos')], default='Sem categoria'),
        ),
    ]
